"""Compatibility wrapper for :mod:`synplan.routes.clustering`."""

from chython.containers import CGRContainer, MoleculeContainer, ReactionContainer
from chython.containers.bonds import DynamicBond

from synplan.routes.analysis import route_cgr_pseudo_reactants_by_role
from synplan.routes.clustering.core import (
    cluster_route_from_csv,
    cluster_route_from_json,
    cluster_routes,
    extract_strat_bonds,
    run_cluster_cli,
)
from synplan.routes.clustering.subclustering import (
    SubclusterError,
    all_lg_collect,
    group_by_identical_values,
    group_routes_by_synthon_detail,
    lg_process_reset,
    lg_reaction_replacer,
    lg_replacer,
    new_lg_reaction_replacer,
    post_process_subgroup,
    remove_and_shift,
    replace_leaving_groups_in_synthon,
    replace_supporting_reactants_with_y,
    subcluster_all_clusters,
    subcluster_one_cluster,
    supporting_groups_from_route_cgr,
)
from synplan.routes.clustering.leaving_groups import DynamicX, Marked, MarkedAt, MarkedY
from synplan.routes.depiction import (
    WideBondDepictCGR,
    cgr_display,
    depict_custom_reaction,
    wide_cgr_renderer,
)
from synplan.routes.io import make_dict, make_json, read_routes_csv, read_routes_json
from synplan.routes.route_cgr import (
    RouteCGRContainer,
    RouteCGRGraph,
    RouteDynamicBond,
    atom_label,
    bond_label,
    compare_route_cgr_dicts,
    compose_all_route_cgrs,
    compose_all_sb_cgrs,
    compose_route_cgr,
    compose_sb_cgr,
    depict_route_cgr,
    enable_route_cgr_container,
    extract_reactions,
    get_clean_mapping,
    get_leaving_groups,
    hash_route_cgrs,
    process_first_reaction,
    process_target_blocks,
    remove_transient_bonds,
    route_atom,
    route_cgr_bucket_fingerprint,
    route_cgr_bucket_hash,
    route_cgr_fingerprint,
    route_cgr_fingerprint_without_route_order,
    route_cgr_graph,
    route_cgr_hash,
    route_cgr_hash_without_route_order,
    route_cgr_metadata,
    route_cgrs_equal,
    route_order_variant_sets,
    transient_bond,
    update_reaction_dict,
    validate_molecule_components,
)
from synplan.utils.visualisation import (
    routes_clustering_report,
    routes_subclustering_report,
)

__all__ = [
    "CGRContainer",
    "DynamicBond",
    "DynamicX",
    "Marked",
    "MarkedAt",
    "MarkedY",
    "MoleculeContainer",
    "ReactionContainer",
    "RouteCGRContainer",
    "RouteCGRGraph",
    "RouteDynamicBond",
    "SubclusterError",
    "WideBondDepictCGR",
    "all_lg_collect",
    "atom_label",
    "bond_label",
    "cgr_display",
    "cluster_route_from_csv",
    "cluster_route_from_json",
    "cluster_routes",
    "compare_route_cgr_dicts",
    "compose_all_route_cgrs",
    "compose_all_sb_cgrs",
    "compose_route_cgr",
    "compose_sb_cgr",
    "depict_custom_reaction",
    "depict_route_cgr",
    "enable_route_cgr_container",
    "extract_reactions",
    "extract_strat_bonds",
    "get_clean_mapping",
    "get_leaving_groups",
    "group_by_identical_values",
    "group_routes_by_synthon_detail",
    "hash_route_cgrs",
    "lg_process_reset",
    "lg_reaction_replacer",
    "lg_replacer",
    "make_dict",
    "make_json",
    "new_lg_reaction_replacer",
    "post_process_subgroup",
    "process_first_reaction",
    "process_target_blocks",
    "read_routes_csv",
    "read_routes_json",
    "remove_and_shift",
    "remove_transient_bonds",
    "replace_leaving_groups_in_synthon",
    "replace_supporting_reactants_with_y",
    "route_atom",
    "route_cgr_bucket_fingerprint",
    "route_cgr_bucket_hash",
    "route_cgr_fingerprint",
    "route_cgr_fingerprint_without_route_order",
    "route_cgr_graph",
    "route_cgr_hash",
    "route_cgr_hash_without_route_order",
    "route_cgr_metadata",
    "route_cgr_pseudo_reactants_by_role",
    "route_cgrs_equal",
    "route_order_variant_sets",
    "routes_clustering_report",
    "routes_subclustering_report",
    "run_cluster_cli",
    "subcluster_all_clusters",
    "subcluster_one_cluster",
    "supporting_groups_from_route_cgr",
    "transient_bond",
    "update_reaction_dict",
    "validate_molecule_components",
    "wide_cgr_renderer",
]
