"""Compatibility wrapper for :mod:`synplan.routes.route_cgr.hash`."""

from synplan.routes.route_cgr.hash import (
    BUCKET_HASH_SCHEMA,
    HASH_EXCLUDES,
    HASH_INCLUDES,
    HASH_SCHEMA,
    ROUTE_ORDER_AGNOSTIC_BUCKET_HASH_SCHEMA,
    ROUTE_ORDER_AGNOSTIC_HASH_SCHEMA,
    RouteCGRGraph,
    atom_label,
    bond_label,
    compare_route_cgr_dicts,
    hash_route_cgrs,
    route_cgr_bucket_fingerprint,
    route_cgr_bucket_hash,
    route_cgr_fingerprint,
    route_cgr_fingerprint_without_route_order,
    route_cgr_graph,
    route_cgr_hash,
    route_cgr_hash_without_route_order,
    route_cgr_metadata,
    route_cgrs_equal,
    route_order_variant_sets,
)

__all__ = [
    "BUCKET_HASH_SCHEMA",
    "HASH_EXCLUDES",
    "HASH_INCLUDES",
    "HASH_SCHEMA",
    "ROUTE_ORDER_AGNOSTIC_BUCKET_HASH_SCHEMA",
    "ROUTE_ORDER_AGNOSTIC_HASH_SCHEMA",
    "RouteCGRGraph",
    "atom_label",
    "bond_label",
    "compare_route_cgr_dicts",
    "hash_route_cgrs",
    "route_cgr_bucket_fingerprint",
    "route_cgr_bucket_hash",
    "route_cgr_fingerprint",
    "route_cgr_fingerprint_without_route_order",
    "route_cgr_graph",
    "route_cgr_hash",
    "route_cgr_hash_without_route_order",
    "route_cgr_metadata",
    "route_cgrs_equal",
    "route_order_variant_sets",
]
