"""Module containing a class Node in the tree search."""


class Node:
    """Node class represents a node in the tree search.

    Carries both the precursor state being expanded and the per-node
    search state recorded by :class:`Tree`.
    """

    def __init__(
        self,
        precursors_to_expand: tuple | None = None,
        new_precursors: tuple | None = None,
        *,
        visit: int = 0,
        depth: int = 0,
        prob: float = 0.0,
        init_value: float = 0.0,
        total_value: float = 0.0,
        rule_id: int | None = None,
        rule_source: str | None = None,
        rule_key: str | None = None,
        policy_rank: int | None = None,
    ) -> None:
        """Initialize the Node object.

        :param precursors_to_expand: The tuple of precursors to be expanded. The first
            precursor in the tuple is the current precursor which will be expanded
            (for which new precursors will be generated by applying the predicted
            reaction rules). When the first precursor has been successfully expanded,
            the second precursor becomes the current precursor to be expanded.
        :param new_precursors: The tuple of new precursors generated by applying the
            reaction rule.

        :param visit: Number of times this node has been visited by the search
            algorithm. Mutated in place during backpropagation.
        :param depth: Tree depth (root = 0; each child = ``parent.depth + 1``).
        :param prob: Prior used for UCB sibling selection. For policy-source
            children, this is the policy probability scaled by the number of
            qualifying product fragments — so ``prob`` stays bounded above by
            the fragment count and is typically in ``[0, 1]``. For
            priority-source children, the rule enters with ``prob = 1.0`` and
            is then multiplied by the qualifying fragment count, so ``Node.prob``
            for an N-fragment priority disconnect equals N (e.g. ``4.0`` for a
            4-component Ugi). This intentionally lets curated priority rules
            outrank policy siblings; PUCT/UCT tolerate super-unit priors.
            ``0.0`` for the root.
        :param init_value: Evaluator-assigned initial value (e.g. rollout reward,
            value-network score, RDKit-based score).
        :param total_value: Running estimate of node value. Updated by
            backpropagation according to the algorithm's rule (running mean for
            UCT/PUCT muzero-style; sum for cumulative).

        :param rule_id: Index of the reaction rule that produced this node, or
            ``None`` for the root.
        :param rule_source: Source namespace of the rule (typically ``"policy"``
            or ``"priority"``), or ``None`` for the root.
        :param rule_key: Collision-safe identifier ``f"{rule_source}:{rule_id}"``,
            or ``None`` whenever either component is missing.
        :param policy_rank: 1-indexed Top-N position from the policy network for
            policy-source rules; ``None`` for priority-source rules and the root.
        """

        self.precursors_to_expand = precursors_to_expand
        self.new_precursors = new_precursors

        if len(self.precursors_to_expand) == 0:
            self.curr_precursor = tuple()
            self.next_precursor: tuple = ()
        else:
            self.curr_precursor = self.precursors_to_expand[0]
            self.next_precursor = self.precursors_to_expand[1:]

        self.visit = visit
        self.depth = depth
        self.prob = prob
        self.init_value = init_value
        self.total_value = total_value

        self.rule_id = rule_id
        self.rule_source = rule_source
        self.rule_key = rule_key
        self.policy_rank = policy_rank

    def __len__(self) -> int:
        """Returns the number of precursor in the node to expand."""
        return len(self.precursors_to_expand)

    def __repr__(self) -> str:
        """Returns the SMILES of each precursor in precursor_to_expand and new_precursor."""
        return (
            f"New precursors: {self.new_precursors}\n"
            f"Precursors to expand: {self.precursors_to_expand}\n"
        )

    def is_solved(self) -> bool:
        """If True, it is a terminal node.

        There are no precursors for expansion.
        """

        return len(self.precursors_to_expand) == 0
