{{- if .Values.synplanner.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
spec:
  accessModes:
    - {{ .Values.synplanner.persistence.accessMode }}
  {{- if .Values.synplanner.persistence.storageClass }}
  storageClassName: {{ .Values.synplanner.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.synplanner.persistence.size }}
{{- end }}
