min_popularity: 3
environment_atom_count: 1
multicenter_rules: True
include_rings: False
include_func_groups: False
func_groups_list: []
keep_leaving_groups: False
keep_incoming_groups: False
keep_reagents: False
atom_info_retention:
  reaction_center:
    neighbors: True
    hybridization: True
    implicit_hydrogens: False
    ring_sizes: False
  environment:
    neighbors: False
    hybridization: False
    implicit_hydrogens: False
    ring_sizes: False